import { Repertorio } from "@/types/repertorio";

export const RepertoriosData: Repertorio[] = [
  // {
  //   id: "000",
  //   title: "Título teste de repertório",

  //   type: "filme",

  //   category: "Violência / Direitos Humanos",

  //   eixoTematico: ["Direitos humanos e cidadania"],

  //   specificThemes: ["Violência contra a mulher", "Desigualdade de gênero"],
  //   keywords: [
  //     "mulher",
  //     "violência",
  //     "proteção",
  //     "lei",
  //     "gênero",
  //     "doméstica",
  //     "maria",
  //     "penha",
  //   ],

  //   explanation:
  //     "Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos. \n\n Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos. \n\n Morbi ut, elementum nullam nam. Elementum nisi gravida duis, eros curabitur tempor, ac felis libero et dui metus quis iaculis. Lacinia erat, quam suspendisse arcu malesuada. Eros fringilla nibh, massa curabitur, maecenas ut nunc eleifend laoreet nisl. Praesent egestas tempor dapibus, pulvinar hac ligula dolor sociosqu. Luctus iaculis elit, risus et, id semper himenaeos tortor leo. Litora consectetur curabitur habitasse, sed ultrices sit, tincidunt dictum rhoncus aliquam per lorem lobortis metus. Auctor id faucibus, commodo praesent, habitasse fermentum vulputate adipiscing nisi.",
  //   essayUsage:
  //     "Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos. \n\n Morbi ut, elementum nullam nam. Elementum nisi gravida duis, eros curabitur tempor, ac felis libero et dui metus quis iaculis. Lacinia erat, quam suspendisse arcu malesuada. Eros fringilla nibh, massa curabitur, maecenas ut nunc eleifend laoreet nisl. Praesent egestas tempor dapibus, pulvinar hac ligula dolor sociosqu. Luctus iaculis elit, risus et, id semper himenaeos tortor leo. Litora consectetur curabitur habitasse, sed ultrices sit, tincidunt dictum rhoncus aliquam per lorem lobortis metus. Auctor id faucibus, commodo praesent, habitasse fermentum vulputate adipiscing nisi.",

  //   usageTemplate:
  //     "Desde a Revolução Industrial, as transformações nas relações de trabalho e na organização social têm gerado impactos profundos na vida humana. No Brasil contemporâneo, essa lógica se manifesta na [problema], em que a busca por flexibilidade oculta a perda de garantias trabalhistas básicas. Assim, torna-se necessário compreender os fatores que sustentam esse cenário. Lorem ipsum dolor sit amet consectetur adipiscing elit. [dado/exemplo] vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. ",

  //   usageTips:
  //     "Substitua [problema] pelo eixo temático da redação. Funciona bem para temas de violência de gênero, proteção da mulher e falhas institucionais.",

  //   usagePlaceholders: ["[problema]", "[dado/exemplo]"],

  //   usageExample: [
  //     "Desafios para fazer um site que recomenda repertórios",
  //     "Desde a Revolução Industrial, as transformações nas relações de trabalho e na organização social têm gerado impactos profundos na vida humana. No Brasil contemporâneo, essa lógica se manifesta na uberização do trabalho, em que a busca por flexibilidade oculta a perda de garantias trabalhistas básicas. Assim, torna-se necessário compreender os fatores que sustentam esse cenário. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. ",
  //   ],

  //   bestFor: "introdução",
  // },
  {
    id: "001",
    title: "Lei Maria da Penha (Lei 11.340/2006)",

    type: "lei",

    category: "Violência / Direitos Humanos",

    eixoTematico: ["Direitos humanos e cidadania"],

    specificThemes: ["Violência contra a mulher", "Desigualdade de gênero"],
    keywords: [
      "mulher",
      "violência",
      "proteção",
      "lei",
      "gênero",
      "doméstica",
      "maria",
      "penha",
    ],

    explanation:
      "Lei brasileira criada para combater a violência doméstica e familiar contra a mulher. Recebeu esse nome em homenagem a Maria da Penha Maia Fernandes.",
    essayUsage:
      "Pode sustentar argumentos sobre violência de gênero, proteção institucional e políticas públicas voltadas para mulheres.",

    usageTemplate:
      "A Lei Maria da Penha (Lei 11.340/2006), criada para combater a violência doméstica e familiar contra a mulher, representa um marco na luta por direitos e proteção feminina no Brasil. Entretanto, [problema] ainda persiste na sociedade brasileira, evidenciando a insuficiência das políticas públicas de enfrentamento.",

    usageTips:
      "Substitua [problema] pelo eixo temático da redação. Funciona bem para temas de violência de gênero, proteção da mulher e falhas institucionais.",

    usagePlaceholders: ["[problema]", "[dado/exemplo]"],

    bestFor: "introdução",
  },
  {
    id: "002",
    title: "Revolução Industrial",
    type: "evento",
    category:
      "Industrialização / Tecnologia / Trabalho / Capitalismo / Desenvolvimento econômico / Transformações sociais / Mecanização",
    eixoTematico: ["Trabalho e economia"],
    specificThemes: [
      "Impactos da industrialização na sociedade",
      "Impactos da tecnologia sobre o trabalho",
      "Substituição da mão de obra por máquinas",
      "Precarização das relações de trabalho",
      "Condições de trabalho",
      "Exploração do trabalhador",
      "Trabalho infantil",
      "Trabalho feminino",
      "Desigualdade social",
      "Desigualdade econômica",
      "Urbanização acelerada",
      "Êxodo rural",
      "Crescimento desordenado das cidades",
      "Industrialização brasileira",
      "Desenvolvimento econômico",
      "Avanço tecnológico",
      "Relação entre tecnologia e emprego",
      "Mecanização agrícola",
      "Impactos da mecanização no campo",
      "Transformação das relações de trabalho",
      "Capitalismo e desigualdade",
      "Consequências sociais do desenvolvimento industrial",
    ],
    keywords: [
      "revolução industrial",
      "primeira revolução industrial",
      "industrialização",
      "inglaterra",
      "século xviii",
      "século xix",
      "máquinas",
      "mecanização",
      "máquina a vapor",
      "indústria",
      "produção industrial",
      "produção em larga escala",
      "fábrica",
      "manufatura",
      "trabalho manual",
      "divisão do trabalho",
      "produtividade",
      "tecnologia",
      "inovação tecnológica",
      "avanço tecnológico",
      "desenvolvimento industrial",
      "capitalismo industrial",
      "capitalismo",
      "sistema fabril",
      "proletariado",
      "classe trabalhadora",
      "burguesia industrial",
      "exploração do trabalho",
      "condições de trabalho",
      "jornada de trabalho",
      "trabalho infantil",
      "trabalho feminino",
      "urbanização",
      "crescimento das cidades",
      "êxodo rural",
      "transformação social",
      "transformação econômica",
      "transformação tecnológica",
      "desigualdade social",
      "desigualdade econômica",
      "relações de trabalho",
      "mercado de trabalho",
      "emprego",
      "desemprego",
      "substituição da mão de obra",
      "mecanização agrícola",
      "industrialização da agricultura",
      "impactos da industrialização",
      "impactos tecnológicos",
      "tecnologia e trabalho",
      "modernização",
      "desenvolvimento econômico",
      "progresso tecnológico",
    ],
    explanation:
      "A Revolução Industrial foi um período de profundas transformações econômicas, tecnológicas e sociais iniciado na Inglaterra, no século XVIII, marcado pela mecanização da produção e pela substituição gradual do trabalho manual por máquinas. A expansão da produção industrial e a busca por maior produtividade modificaram as relações de trabalho e contribuíram para mudanças na organização da sociedade. Entre seus impactos, destaca-se a transformação do trabalho no campo, posteriormente intensificada pela mecanização agrícola e pela expansão da produção em larga escala.",
    essayUsage:
      "O repertório pode ser utilizado para discutir as transformações provocadas pela mecanização e pelo desenvolvimento tecnológico nas relações de trabalho. É especialmente produtivo para temas relacionados à valorização do trabalhador rural, às condições de trabalho no campo, à precarização profissional, aos impactos da tecnologia sobre o emprego, à mecanização agrícola e aos riscos enfrentados pelos trabalhadores rurais.",
    usageTemplate:
      "A Revolução Industrial, que teve início na Inglaterra, no século XVIII, foi um período de grandes transformações tecnológicas. Tal fenômeno atingiu em cheio o homem do campo. A mecanização e a exigência de produção em larga escala fizeram com que o trabalho manual fosse cada vez mais relegado ao segundo plano. Aqueles que persistem estão expostos a toda sorte de riscos, que vão de remunerações injustas à intoxicação por agrotóxicos. No entanto, [tema] passa pelo enfrentamento de dois desafios históricos.",
    usagePlaceholders: ["[tema]"],
    usageTips:
      "No campo [tema], reescreva com outras palavras o tema proposto pelo caderno de redação.",
    usageExample: [
      "A valorização do trabalhador rural na sociedade brasileira",
      "A Revolução Industrial, que teve início na Inglaterra, no século XVIII, foi um período de grandes transformações tecnológicas. Tal fenômeno atingiu em cheio o homem do campo. A mecanização e a exigência de produção em larga escala fizeram com que o trabalho manual fosse cada vez mais relegado ao segundo plano. Aqueles que persistem estão expostos a toda sorte de riscos, que vão de remunerações injustas à intoxicação por agrotóxicos. No entanto, a valorização do trabalhador rural no Brasil passa pelo enfrentamento de dois desafios históricos.",
    ],
    bestFor: "introdução",
  },
  {
    id: "003",
    title: "Que Horas Ela Volta?",
    type: "filme",
    category: "Desigualdade Social / Trabalho / Educação / Xenofobia",
    eixoTematico: ["Desigualdade e inclusão", "Trabalho e economia"],
    specificThemes: [
      "Desigualdade socioeconômica",
      "Relações de trabalho",
      "Trabalho doméstico",
      "Divisão de classes",
      "Mobilidade social",
      "Acesso à educação",
      "Privilégios de classe",
    ],
    keywords: [
      "desigualdade",
      "trabalho",
      "socioeconômica",
      "educação",
      "privilégios",
      "doméstico",
      "relações de trabalho",
      "mobilidade social",
      "classes",
      "xenofobia",
      "nordestina",
      "preconceito regional",
      "migração interna",
      "hierarquia social",
      "oportunidades",
      "nordeste",
    ],
    explanation:
      '"Que Horas Ela Volta?" é um filme brasileiro dirigido por Anna Muylaert, lançado em 2015. A obra acompanha Val, uma empregada doméstica que trabalha na casa de uma família de classe alta em São Paulo. A chegada de sua filha, Jéssica, evidencia as diferenças sociais presentes naquele ambiente, especialmente por meio das relações entre empregados e patrões. O filme aborda como as desigualdades de classe influenciam o acesso a espaços, oportunidades e direitos, além de questionar a naturalização das hierarquias sociais.',
    essayUsage:
      "O filme pode ser utilizado para evidenciar como a desigualdade social ultrapassa a diferença de renda e também se manifesta no acesso a oportunidades, espaços e direitos. A relação entre Val e os patrões permite discutir a desigualdade nas relações de trabalho, especialmente no trabalho doméstico. Já a trajetória de Jéssica pode ser relacionada à educação e à mobilidade social, mostrando como o acesso a oportunidades pode desafiar posições sociais tradicionalmente estabelecidas. O repertório também pode ser usado para problematizar a naturalização dos privilégios de determinados grupos sociais, além de retratar a xenofobia sofrida pela personagem Jéssica por ser nordestina.",
    usageTemplate:
      'No filme brasileiro "Que Horas Ela Volta?", dirigido por Anna Muylaert, a relação entre a empregada doméstica Val e a família para a qual trabalha evidencia como as diferenças de classe influenciam o acesso a espaços e oportunidades. De maneira semelhante, na realidade brasileira, [problema] revela a permanência de desigualdades que ultrapassam o aspecto econômico e dificultam [consequência do tema].',
    usagePlaceholders: ["[problema]", "[consequência]"],
    usageTips:
      'No campo [problema], coloque o principal problema apresentado pelo tema da redação. Em [consequência do tema], indique o efeito provocado por esse problema. O repertório funciona melhor quando o tema envolve desigualdade, trabalho, educação, oportunidades, privilégios sociais ou mobilidade social. Evite utilizar o filme apenas para afirmar que "existe desigualdade"; relacione uma situação da obra ao problema discutido na redação.',
    usageExample: [
      "Desafios para combater a desigualdade social no Brasil",
      'No filme brasileiro "Que Horas Ela Volta?", dirigido por Anna Muylaert, a relação entre a empregada doméstica Val e a família para a qual trabalha evidencia como as diferenças de classe influenciam o acesso a espaços e oportunidades. De maneira semelhante, na sociedade brasileira, a desigualdade social ainda limita o acesso de parte da população a direitos e oportunidades, uma vez que condições socioeconômicas distintas contribuem para a manutenção de privilégios e dificultam a mobilidade social.',
    ],
    bestFor: "introdução",
  },
  {
    id: "004",
    title: "Declaração Universal do Direito Humano (DUDH)",
    type: "lei",
    category: "Direitos Humanos / Cidadania / Direitos Sociais",
    eixoTematico: ["Direitos humanos e cidadania", "Desigualdade e inclusão"],
    specificThemes: [
      "Direitos fundamentais",
      "Dignidade humana",
      "Igualdade",
      "Liberdade",
      "Cidadania",
      "Discriminação",
      "Desigualdade social",
      "Acesso a direitos",
      "Direitos sociais",
      "Violência",
      "Educação",
      "Saúde",
      "Trabalho",
      "Moradia",
      "Liberdade de expressão",
    ],
    keywords: [
      "direitos humanos",
      "dignidade",
      "igualdade",
      "liberdade",
      "cidadania",
      "direitos fundamentais",
      "discriminação",
      "direitos sociais",
      "onu",
      "educação",
      "saúde",
      "trabalho",
      "moradia",
      "documento",
      "dudh",
    ],
    explanation:
      "A Declaração Universal dos Direitos Humanos (DUDH) é um documento adotado pela Organização das Nações Unidas (ONU) em 1948, que estabelece princípios e direitos fundamentais que devem ser assegurados a todas as pessoas, independentemente de características como origem, sexo, religião ou condição social. O documento defende princípios como liberdade, igualdade, dignidade e direito à segurança, além de reconhecer direitos relacionados à educação, ao trabalho e à participação social.",
    essayUsage:
      "A DUDH pode ser utilizada para demonstrar que determinado problema social representa uma violação ou um obstáculo à garantia de direitos fundamentais. O repertório é especialmente útil quando o tema envolve desigualdade, discriminação, violência, acesso à educação, saúde, trabalho, moradia ou cidadania. Também pode ser utilizado para estabelecer uma relação entre o princípio de dignidade humana e situações em que parte da população não possui seus direitos efetivamente garantidos.",
    usageTemplate:
      "Em 1948, a ONU promulgou a Declaração Universal dos Direitos Humanos, como resposta imediata às atrocidades cometidas nas duas guerras mundiais. Mais do que isso, a entidade visava a garantir a todos condições mínimas de sobrevivência em ambiente de respeito, igualdade e liberdade. O Brasil foi signatário e militante ativo dessa declaração. Entretanto, é inegável que o país ainda está distante de concretizar os ideais desse documento. Prova disso é que boa parte dos brasileiros ainda convive com graves ameaças à sua qualidade de vida. É o caso do/da [problema]. Segundo [dado / exemplo / explicação]. Esse é um problema forjado sobre duas causas históricas.",
    usagePlaceholders: ["[problema]", "[dado / exemplo / explicação]"],
    usageTips:
      "No campo [problema], coloque o problema central apresentado pelo tema. No segundo placeholder, acrescente um dado estatístico, exemplo concreto ou explicação que comprove a existência desse problema. A estrutura funciona melhor quando o problema apresentado pode ser relacionado à violação ou à dificuldade de concretização dos princípios de igualdade, liberdade, respeito e dignidade defendidos pela Declaração.",
    usageExample: [
      "Desafios para garantir o acesso à educação de qualidade no Brasil",
      "Em 1948, a ONU promulgou a Declaração Universal dos Direitos Humanos, como resposta imediata às atrocidades cometidas nas duas guerras mundiais. Mais do que isso, a entidade visava a garantir a todos condições mínimas de sobrevivência em ambiente de respeito, igualdade e liberdade. O Brasil foi signatário e militante ativo dessa declaração. Entretanto, é inegável que o país ainda está distante de concretizar os ideais desse documento. Prova disso é que boa parte dos brasileiros ainda convive com graves ameaças à sua qualidade de vida. É o caso da desigualdade no acesso à educação de qualidade. Segundo [dado estatístico ou exemplo sobre a desigualdade educacional], parte da população brasileira ainda enfrenta dificuldades para usufruir de uma formação adequada. Esse é um problema forjado sobre duas causas históricas.",
    ],
    bestFor: "introdução",
  },
  {
    id: "005",
    title: "Ensaio sobre a cegueira",
    type: "livro",
    category:
      "Empatia / Cidadania / Solidariedade / Individualismo / Invisibilidade Social / Responsabilidade Coletiva",
    eixoTematico: ["Cultura e sociedade", "Direitos humanos e cidadania"],
    specificThemes: [
      "Indiferença social",
      "Invisibilidade social",
      "Individualismo",
      "Falta de empatia",
      "Exclusão social",
      "Responsabilidade coletiva",
      "Naturalização de problemas sociais",
    ],
    keywords: [
      "empatia",
      "indiferença",
      "invisibilidade social",
      "individualismo",
      "solidariedade",
      "responsabilidade coletiva",
      "exclusão",
      "cegueira social",
      "josé saramago",
    ],
    explanation:
      '"Ensaio sobre a cegueira" é um romance do escritor português José Saramago, publicado em 1995. A obra apresenta uma sociedade atingida por uma epidemia de cegueira, que provoca desorganização social e expõe diferentes comportamentos humanos diante de uma situação extrema. A cegueira apresentada na narrativa também funciona como uma metáfora para a incapacidade de enxergar o outro, seus problemas e suas necessidades, evidenciando o individualismo e a ausência de empatia nas relações sociais.',
    essayUsage:
      "O repertório pode ser utilizado para discutir problemas cuja permanência esteja relacionada à indiferença da sociedade ou à dificuldade de reconhecer a realidade vivenciada por determinados grupos. A metáfora da cegueira permite relacionar a falta de empatia e o individualismo à naturalização de problemas sociais, mostrando que aquilo que não é devidamente percebido ou reconhecido pela coletividade tende a permanecer invisível.",
    usageTemplate:
      'Além disso, o [argumento 2] é outro desafio. Baseadas em valores ultrapassados, muitas pessoas acabam por normalizar condutas e situações que deveriam ser repudiadas. Nesse contexto, mazelas como a [tema] persistem porque são sustentadas por uma percepção errada por boa parte da população sobre o tema. Ou seja, enquanto o conhecimento partilhado pela maioria não for suficiente para alcançar os impactos dessa falta de valorização, o problema dificilmente será sanado. Isso porque, assim como sugere José Saramago na obra "Ensaio sobre a cegueira", a incapacidade das pessoas de ver o outro gera uma sociedade de indivíduos autocentrados e incapazes de exercer a empatia.',
    usagePlaceholders: ["[argumento 2]", "[tema]"],
    usageTips:
      "Em [TEMA], reescreva com outras palavras o tema proposto pelo caderno de redação. O repertório é especialmente adequado quando o tema envolve invisibilidade, negligência, indiferença ou naturalização de uma questão social.",
    usageExample: [
      "Desafios para o enfrentamento da invisibilidade do trabalho de cuidado realizado pela mulher no Brasil",
      'Além disso, o imaginário coletivo distorcido é outro desafio. Baseadas em valores ultrapassados, muitas pessoas acabam por normalizar condutas e situações que deveriam ser repudiadas. Nesse contexto, mazelas como a invisibilidade do trabalho de cuidado realizado pela mulher persistem porque são sustentadas por uma percepção errada por boa parte da população sobre o tema. Ou seja, enquanto o conhecimento partilhado pela maioria não for suficiente para alcançar os impactos dessa falta de valorização, o problema dificilmente será sanado. Isso porque, assim como sugere José Saramago na obra "Ensaio sobre a cegueira", a incapacidade das pessoas de ver o outro gera uma sociedade de indivíduos autocentrados e incapazes de exercer a empatia.',
    ],
    bestFor: "desenvolvimento",
  },
  {
    id: "006",
    title: "O Dilema das Redes",
    type: "documentario",
    category:
      "Tecnologia / Redes Sociais / Privacidade / Saúde Mental / Manipulação da Informação",
    eixoTematico: [
      "Tecnologia e inovação",
      "Saúde",
      "Política e relações sociais",
    ],
    specificThemes: [
      "Uso excessivo das redes sociais",
      "Dependência tecnológica",
      "Manipulação comportamental",
      "Coleta de dados",
      "Privacidade digital",
      "Disseminação de desinformação",
      "Polarização social",
      "Saúde mental",
      "Influência dos algoritmos",
      "Consumo de informação",
    ],
    keywords: [
      "redes sociais",
      "algoritmos",
      "privacidade",
      "dados pessoais",
      "desinformação",
      "dependência digital",
      "saúde mental",
      "manipulação",
      "polarização",
      "tecnologia",
    ],
    explanation:
      '"O Dilema das Redes" é um documentário de 2020 dirigido por Jeff Orlowski. A obra combina depoimentos de ex-executivos de Big Techs e cenas dramatizadas para revelar como as redes sociais utilizam algoritmos persuasivos e manipulação psicológica para viciar os usuários, monitorar seus comportamentos e monetizar sua atenção. O documentário alerta que a busca desenfreada por engajamento transforma os próprios usuários no produto comercializado pelas plataformas, gerando consequências graves para a sociedade, como o avanço da polarização política, a disseminação de desinformação em massa e a deterioração da saúde mental, especialmente entre os jovens.',
    essayUsage:
      "O documentário pode ser utilizado para discutir como o funcionamento das redes sociais influencia o comportamento dos usuários e a circulação de informações. Também permite abordar problemas relacionados à privacidade, à coleta de dados, à dependência tecnológica, à desinformação e aos impactos das plataformas digitais sobre a saúde mental. O repertório é especialmente interessante quando o tema envolve os efeitos sociais do uso das tecnologias digitais, pois permite relacionar o problema não apenas ao comportamento do usuário, mas também à estrutura das próprias plataformas.",
    usageTemplate:
      'O documentário "O Dilema das Redes" apresenta os mecanismos utilizados pelas plataformas digitais para influenciar o comportamento dos usuários. Nesse contexto, as redes sociais passaram a ocupar um espaço significativo na vida cotidiana, mas seu funcionamento também contribui para [problema]. No Brasil, [dado/exemplo/explicação]. Assim, para enfrentar [tema], é preciso superar dois desafios históricos.',
    usagePlaceholders: ["[problema]", "[dado/exemplo/explicação]", "[tema]"],
    usageTips:
      "No campo [PROBLEMA], coloque o principal problema apresentado pelo tema da redação. No segundo placeholder, acrescente um dado estatístico, exemplo concreto ou explicação que comprove a existência desse problema. Em [TEMA], reescreva com outras palavras o tema proposto pelo caderno de redação. O repertório funciona melhor quando o tema envolve redes sociais, tecnologia, informação, privacidade ou comportamento digital.",
    usageExample: [
      "Desafios para combater a disseminação de desinformação nas redes sociais brasileiras",
      'O documentário "O Dilema das Redes" apresenta os mecanismos utilizados pelas plataformas digitais para influenciar o comportamento dos usuários. Nesse contexto, as redes sociais passaram a ocupar um espaço significativo na circulação de informações, mas seu funcionamento também contribui para a disseminação de conteúdos enganosos. No Brasil, a ampla utilização dessas plataformas amplia o alcance de informações cuja veracidade nem sempre é verificada. Assim, para combater a divulgação de fake news na internet, é preciso superar dois desafios históricos: a lógica de funcionamento dos algoritmos e a insuficiência da educação midiática.',
    ],
    bestFor: "introdução",
  },
  {
    id: "007",
    title: "Adolescência",
    type: "serie",
    category:
      "Violência de gênero / Redes sociais / Adolescência / Machismo / Saúde mental",
    eixoTematico: ["Diversidade e questões sociais"],
    specificThemes: [
      "Violência contra a mulher no ambiente digital",
      "Misoginia nas redes sociais",
      "Influência das comunidades virtuais na formação dos adolescentes",
      "Masculinidade tóxica",
      "Discurso de ódio contra mulheres",
      "Violência de gênero entre jovens",
      "Influência das redes sociais sobre adolescentes",
      "Formação de valores na adolescência",
      "Responsabilidade da família e da escola na formação dos jovens",
      "Normalização da violência contra a mulher",
    ],
    keywords: [
      "adolescência",
      "adolescentes",
      "jovens",
      "violência contra a mulher",
      "violência de gênero",
      "violência contra meninas",
      "violência digital",
      "violência virtual",
      "violência online",
      "agressão de gênero",
      "misoginia",
      "machismo",
      "cultura machista",
      "ódio contra mulheres",
      "discurso de ódio",
      "discurso misógino",
      "comunidades misóginas",
      "masculinidade",
      "masculinidade tóxica",
      "comportamento masculino",
      "relações de gênero",
      "desigualdade de gênero",
      "preconceito de gênero",
      "discriminação contra mulheres",
      "ataques contra mulheres",
      "assédio virtual",
      "assédio online",
      "cyberbullying",
      "bullying",
      "redes sociais",
      "internet",
      "ambiente digital",
      "mundo virtual",
      "plataformas digitais",
      "comunidades virtuais",
      "influência da internet",
      "influência das redes sociais",
      "exposição nas redes",
      "comportamento nas redes sociais",
      "adolescentes na internet",
      "jovens nas redes sociais",
      "influência digital",
      "influência dos pares",
      "pressão social",
      "pressão dos grupos",
      "formação de valores",
      "formação da identidade",
      "socialização",
      "educação dos jovens",
      "relações entre adolescentes",
      "violência escolar",
      "escola",
      "família",
      "saúde mental dos adolescentes",
      "vulnerabilidade juvenil",
      "radicalização online",
      "conteúdo misógino",
      "normalização da violência",
      "naturalização da violência",
      "ódio online",
      "intolerância",
      "preconceito",
      "sexualização",
      "julgamento do corpo feminino",
      "aparência feminina",
      "comportamento feminino",
      "estereótipos de gênero",
      "estereótipos femininos",
      "violência psicológica",
      "violência moral",
      "violência contra meninas na internet",
      "misoginia online",
      "extremismo online",
      "comunidades de ódio",
    ],
    explanation:
      '"Adolescência" é uma série que acompanha a investigação do assassinato de uma garota supostamente cometido por um colega de escola. Ao longo da trama, a narrativa também aborda a influência de conteúdos e comportamentos presentes no ambiente digital, especialmente aqueles relacionados à misoginia e à violência de gênero entre jovens. A obra evidencia como relações sociais, grupos de pares e conteúdos consumidos na internet podem participar da formação de comportamentos e valores durante a adolescência.',
    essayUsage:
      "A série pode ser utilizada para discutir a influência do ambiente digital na formação dos adolescentes e sua relação com a reprodução de comportamentos machistas e violentos. Também permite abordar a disseminação de discursos de ódio contra mulheres, a normalização da violência de gênero e a influência de comunidades virtuais sobre jovens. O repertório é especialmente produtivo quando o tema relaciona adolescência, internet e violência de gênero, mas também pode ser aplicado a discussões sobre formação de valores, responsabilidade familiar e escolar e impactos das redes sociais.",
    usageTemplate:
      'A série "Adolescência" aborda o assassinato de uma garota supostamente cometido por um colega de escola e apresenta, ao longo da trama, a influência de comportamentos misóginos disseminados no ambiente digital. Nesse contexto, [problema] não se restringe à ficção, uma vez que [dado/exemplo/explicação]. Assim, para enfrentar [tema], é necessário compreender as causas relacionadas a [argumento 1] e [argumento 2].',
    usagePlaceholders: [
      "[problema]",
      "[dado/exemplo/explicação]",
      "[tema]",
      "[argumento 1]",
      "[argumento 2]",
    ],
    usageTips:
      "No campo [problema], coloque o principal problema apresentado pelo tema da redação; em [dado/exemplo/explicação], coloque uma informação, situação concreta ou explicação que comprove ou contextualize o problema apresentado; no campo [tema], reescreva com outras palavras o tema proposto pelo caderno de redação; em [argumento 1] e [argumento 2], coloque as duas principais causas ou fatores que contribuem para a existência ou permanência do problema.",
    usageExample: [
      "Desafios para o enfrentamento da violência contra mulheres nas redes sociais",
      'A série "Adolescência" aborda o assassinato de uma garota supostamente cometido por um colega de escola. A trama, no entanto, se move com uma digressão que mostra uma rotina de agressões de gênero cometida por meninos na internet. Esse contexto não está restrito à ficção. Segundo a SaferNet, em 2024, havia 137 canais abertos na internet cujo conteúdo era voltado a disseminar o ódio contra mulheres. Esses ambientes digitais julgam mulheres por seu tipo corporal, comportamento e até idade. Para frear o crescimento da violência contra mulheres nas redes sociais, no entanto, é preciso conhecer as causas desse fenômeno.',
    ],
    bestFor: "introdução",
  },
  {
    id: "008",
    title: "O Conto da Aia",
    type: "serie",
    category:
      "Direitos Humanos / Direitos das Mulheres / Violência de Gênero / Cidadania / Autoritarismo",
    eixoTematico: ["Direitos humanos e cidadania"],
    specificThemes: [
      "Violência contra mulheres na política",
      "Violência de gênero",
      "Desigualdade de gênero",
      "Participação política feminina",
      "Direitos das mulheres",
      "Direitos reprodutivos",
      "Controle sobre o corpo feminino",
      "Opressão feminina",
      "Autoritarismo",
      "Discriminação contra mulheres",
      "Sub-representação feminina",
    ],
    keywords: [
      "o conto da aia",
      "mulheres",
      "mulher",
      "direitos das mulheres",
      "direitos femininos",
      "direitos reprodutivos",
      "violência contra a mulher",
      "violência de gênero",
      "violência política",
      "desigualdade de gênero",
      "opressão feminina",
      "opressão de gênero",
      "discriminação contra mulheres",
      "misoginia",
      "patriarcado",
      "machismo",
      "dominação masculina",
      "controle sobre o corpo feminino",
      "controle reprodutivo",
      "autonomia feminina",
      "liberdade feminina",
      "liberdade sexual",
      "liberdade reprodutiva",
      "repressão",
      "autoritarismo",
      "totalitarismo",
      "estado autoritário",
      "regime totalitário",
      "estado e mulheres",
      "poder político",
      "participação política feminina",
      "representação feminina",
      "mulheres na política",
      "violência contra mulheres na política",
      "violência política de gênero",
      "assédio político",
      "ameaças contra mulheres",
      "agressão política",
      "exclusão política",
      "sub-representação feminina",
      "participação feminina",
      "igualdade de gênero",
      "equidade de gênero",
      "direitos políticos",
      "cidadania feminina",
      "emancipação feminina",
      "discriminação política",
      "perseguição política",
      "direitos civis",
      "direitos fundamentais",
      "liberdade",
      "dignidade",
      "autonomia",
      "abuso de poder",
      "controle social",
      "repressão estatal",
      "fundamentalismo religioso",
      "religião e política",
      "poder sobre o corpo",
      "exploração reprodutiva",
      "objetificação feminina",
      "estereótipos de gênero",
      "papéis de gênero",
      "submissão feminina",
      "invisibilidade política",
      "mulheres eleitas",
      "mulheres em cargos políticos",
    ],
    explanation:
      'Conto da Aia (The Handmaid\'s Tale) se passa em um futuro distópico no qual uma crise global de fertilidade leva à ascensão de Gilead, uma teocracia totalitária e fundamentalista religiosa erguida no território dos antigos Estados Unidos. A narrativa acompanha June Osborne (Offred), uma mulher fértil despojada de sua identidade, separada de sua família e submetida à escravidão sexual ritualizada como uma "Aia" para gerar filhos aos comandantes da elite dominante. Ao longo da trama, o enredo retrata a brutalidade da privação dos direitos das mulheres e a rotina sob constante vigilância, acompanhando a evolução de June de uma sobrevivente fragilizada para uma peça-chave da resistência secreta na luta para escapar do regime, resgatar sua filha e combater a opressão de Gilead.',
    essayUsage:
      "O repertório pode ser utilizado para discutir situações em que mulheres têm sua liberdade, seus direitos ou sua participação social e política limitados pela violência e pela desigualdade de gênero. A obra é especialmente produtiva para temas relacionados à violência contra mulheres na política, aos direitos reprodutivos, à participação feminina nos espaços de poder e à permanência de estruturas sociais que restringem a autonomia das mulheres.",
    usageTemplate:
      'O livro "O Conto da Aia" ambienta-se em um futuro distópico em que mulheres têm todos os direitos negados, sendo reduzidas à função reprodutiva e submetidas a situações deploráveis. A abordagem desse tema na obra evidencia como [problema] é um meio utilizado para negar direitos às mulheres, situação ainda presente na sociedade. Tal arbitrariedade, no entanto, não se restringe [contexto]. Segundo [dado/explicação/exemplo], [comprovação do problema]. Entretanto, para enfrentar [tema], o Brasil precisará vencer alguns desafios históricos.',
    usagePlaceholders: [
      "[problema]",
      "[contexto]",
      "[dado/exemplo/explicação]",
      "[comprovação do problema]",
      "[tema]",
    ],
    usageTips:
      "No campo [problema], coloque o principal problema apresentado pelo tema da redação; em [contexto], coloque o espaço, situação ou dimensão em que o problema também se manifesta; em [dado/exemplo/explicação], coloque uma informação, situação concreta ou explicação que comprove ou contextualize o problema apresentado; em [comprovação do problema], apresente o dado, exemplo ou explicação selecionado de forma relacionada ao problema discutido; no campo [tema], reescreva com outras palavras o tema proposto pelo caderno de redação.",
    usageExample: [
      "O enfrentamento da violência contra mulheres na política no Brasil",
      'O livro "O Conto da Aia" ambienta-se em um futuro distópico em que mulheres têm todos os direitos negados, sendo reduzidas à função reprodutiva e submetidas a situações deploráveis. A abordagem desse tema na obra evidencia como a violência de gênero é um meio utilizado para negar direitos às mulheres, situação ainda comum em todo o mundo. Tal arbitrariedade, no entanto, não se restringe ao ambiente doméstico. Segundo a OEA e a Fundação Getúlio Vargas, 45% das mulheres eleitas para cargos legislativos no Brasil já sofreram algum tipo de violência política, como agressão física, insultos e ameaças. Entretanto, para enfrentar a violência política contra mulheres, o Brasil precisará vencer alguns desafios históricos.',
    ],
    bestFor: "introdução",
  },
  {
    id: "009",
    title: "Segunda Chamada",
    type: "serie",
    category:
      "Educação / Valorização profissional / Trabalho / Desigualdade social / Educação de jovens e adultos / Inclusão social",
    eixoTematico: ["Educação"],
    specificThemes: [
      "Valorização do professor no Brasil",
      "Desvalorização dos professores",
      "Reconhecimento social dos docentes",
      "Condições de trabalho dos professores",
      "Remuneração docente",
      "Precarização do trabalho docente",
      "Infraestrutura das escolas públicas",
      "Educação pública brasileira",
      "Educação de jovens e adultos",
      "Evasão escolar",
      "Permanência de estudantes na escola",
      "Desigualdade educacional",
      "Violência no ambiente escolar",
      "Preconceito no ambiente escolar",
      "Desafios da profissão docente",
    ],
    keywords: [
      "segunda chamada",
      "educação",
      "educação pública",
      "escola pública",
      "professores",
      "professor",
      "valorização do professor",
      "desvalorização docente",
      "reconhecimento profissional",
      "prestígio social",
      "trabalho docente",
      "profissão docente",
      "carreira docente",
      "condições de trabalho",
      "precarização do trabalho docente",
      "remuneração dos professores",
      "baixos salários",
      "infraestrutura escolar",
      "falta de infraestrutura",
      "respeito profissional",
      "reconhecimento social",
      "eja",
      "educação de jovens e adultos",
      "ensino noturno",
      "alfabetização",
      "evasão escolar",
      "abandono escolar",
      "preconceito na escola",
      "violência escolar",
      "dificuldades educacionais",
      "desigualdade educacional",
      "acesso à educação",
      "permanência escolar",
      "ensino público",
      "desafios da educação brasileira",
      "condições de ensino",
      "cotidiano escolar",
      "docentes do ensino básico",
      "professores da rede pública",
    ],
    explanation:
      "A série brasileira \"Segunda Chamada\", produzida pela TV Globo, acompanha o cotidiano de uma escola pública localizada na periferia de São Paulo que oferece aulas de Educação de Jovens e Adultos (EJA) no período noturno. A trama apresenta professores e estudantes que, apesar das dificuldades sociais e econômicas, buscam concluir a educação básica. Ao longo da narrativa, são retratadas situações como evasão escolar, violência, preconceito, vulnerabilidade social e falta de recursos, além dos desafios enfrentados pelos profissionais da educação no exercício de seu trabalho. Dessa forma, a série evidencia obstáculos relacionados ao acesso e à permanência na educação básica, além de questões como desigualdade educacional, valorização dos professores e condições da educação pública brasileira.",
    essayUsage:
      "O repertório pode ser utilizado para discutir problemas relacionados à educação pública e às condições enfrentadas por professores e estudantes no Brasil. É especialmente produtivo para temas sobre valorização e reconhecimento profissional dos docentes, remuneração e condições de trabalho, infraestrutura escolar, educação de jovens e adultos, evasão escolar, desigualdade educacional e violência no ambiente escolar. A série permite relacionar as dificuldades presentes no cotidiano escolar às condições estruturais que interferem na atuação dos professores e na qualidade da educação.",
    usageTemplate:
      'A série da TV Globo "Segunda Chamada" aborda o cotidiano de uma escola pública que oferece educação a jovens e adultos (EJA), no período noturno. Na trama, os professores se deparam com mazelas como evasão escolar, preconceito e violência, que dificultam o trabalho de alfabetização. A abordagem desse tema na produção evidencia a sua relevância no mundo real e dialoga com o Brasil contemporâneo, em que, [dado/explicação/exemplo]. Entretanto, para se [tema], é preciso enfrentar dois desafios históricos.',
    usagePlaceholders: ["[dado/explicação/exemplo]", "[tema]"],
    usageTips:
      "Em [dado/explicação/exemplo], insira um dado estatístico, exemplo concreto ou explicação que comprove ou contextualize o problema abordado pelo tema. Em [tema], reescreva o tema da redação como uma ação, já que o trecho é construído como \"para se [tema]\" (ex.: 'valorizar o professor no Brasil').",
    usageExample: [
      "Desafios à valorização do professor no Brasil",
      'A série da TV Globo "Segunda Chamada" aborda o cotidiano de uma escola pública que oferece educação a jovens e adultos (EJA), no período noturno. Na trama, os professores se deparam com mazelas como evasão escolar, preconceito e violência, que dificultam o trabalho de alfabetização. A abordagem desse tema na produção evidencia a sua relevância no mundo real e dialoga com o Brasil contemporâneo, em que, segundo pesquisa do Ipea, mais de 60% dos docentes do ensino básico afirmam sentir-se desprestigiados pela sociedade, o que reflete baixos salários, falta de infraestrutura e desrespeito profissional. Entretanto, para se valorizar o professor no Brasil, é preciso enfrentar dois desafios históricos.',
    ],
    bestFor: "introdução",
  },
  {
    id: "010",
    title: "Round 6",
    type: "serie",
    category:
      "Desigualdade Social / Desigualdade Econômica / Capitalismo / Individualismo / Ética / Trabalho / Saúde Mental",
    eixoTematico: ["Desigualdade e inclusão"],
    specificThemes: [
      "Ludopatia",
      "Vício em apostas",
      "Apostas esportivas",
      "Apostas online",
      "Endividamento",
      "Impactos sociais das apostas",
      "Impactos econômicos das apostas",
      "Saúde mental",
      "Desigualdade social",
      "Desigualdade econômica",
      "Vulnerabilidade financeira",
      "Precarização do trabalho",
      "Desemprego",
      "Falta de oportunidades",
      "Exploração econômica",
      "Individualismo",
      "Competição social",
      "Concentração de renda",
      "Desigualdade de oportunidades",
    ],
    keywords: [
      "round 6",
      "jogos",
      "competição",
      "dinheiro",
      "recompensa financeira",
      "ambição",
      "ganância",
      "desigualdade social",
      "desigualdade econômica",
      "pobreza",
      "vulnerabilidade econômica",
      "endividamento",
      "dificuldades financeiras",
      "concentração de renda",
      "capitalismo",
      "individualismo",
      "competição social",
      "exploração",
      "exploração econômica",
      "sobrevivência",
      "pressão financeira",
      "precarização do trabalho",
      "desemprego",
      "falta de oportunidades",
      "mobilidade social",
      "consumo",
      "apostas",
      "jogos de azar",
      "vício em apostas",
      "ludopatia",
      "dependência em apostas",
      "bets",
      "apostas esportivas",
      "compulsão",
      "dependência",
      "saúde mental",
      "comportamento compulsivo",
      "perda financeira",
      "endividamento por apostas",
      "consequências das apostas",
      "vulnerabilidade social",
      "desigualdade de oportunidades",
      "jogos mortais",
      "competição por dinheiro",
    ],
    explanation:
      'A série sul-coreana "Round 6" acompanha pessoas endividadas e em situação de vulnerabilidade financeira que aceitam participar de uma competição composta por jogos infantis em troca de uma grande recompensa em dinheiro. Ao longo da narrativa, os participantes são submetidos a situações extremas e passam a competir pela sobrevivência enquanto a promessa de riqueza alimenta sua permanência no jogo. A produção evidencia como dificuldades econômicas, endividamento e desigualdade podem levar indivíduos a situações de exploração e risco, além de abordar questões relacionadas à ambição, ao individualismo e à busca por dinheiro.',
    essayUsage:
      "O repertório pode ser utilizado para discutir problemas relacionados à desigualdade econômica, à vulnerabilidade financeira e às consequências da busca por dinheiro em contextos de dificuldade social. Também é produtivo para temas relacionados à ludopatia, às apostas esportivas, ao endividamento, à saúde mental, à precarização do trabalho e à desigualdade de oportunidades, especialmente quando o tema envolve fatores econômicos que influenciam as escolhas dos indivíduos.",
    usageTemplate:
      'Na série da Netflix "Round 6", pessoas são compelidas a participar de jogos em troca de uma recompensa em dinheiro. Na trama, a ambição dos jogadores é constantemente alimentada com a promessa de maior retorno financeiro. Ao final, no entanto, o que se impõe é a percepção de que a vida deles depende de continuar o jogo. [problema] é um tema que não se restringe ao universo ficcional. Para se ter uma ideia, no Brasil, [dado/exemplo/explicação]. Entretanto, para se enfrentar [tema], é preciso, antes, vencer dois grandes desafios.',
    usagePlaceholders: ["[problema]", "[dado/exemplo/explicação]", "[tema]"],
    usageTips:
      "No campo [problema], coloque o principal problema apresentado pelo tema da redação; em [dado/exemplo/explicação], coloque uma informação, situação concreta ou explicação que comprove ou contextualize o problema apresentado; no campo [tema], reescreva com outras palavras o tema proposto pelo caderno de redação.",
    usageExample: [
      "O enfrentamento à ludopatia na sociedade brasileira",
      'Na série da Netflix "Round 6", pessoas são compelidas a participar de jogos em troca de uma recompensa em dinheiro. Na trama, a ambição dos jogadores é constantemente alimentada com a promessa de maior retorno financeiro. Ao final, no entanto, o que se impõe é a percepção de que a vida deles depende de continuar o jogo. O vício em apostas, ou ludopatia, é um tema que não se restringe ao universo ficcional. Para se ter uma ideia, no Brasil, 64% dos jogadores assumem deixar de fazer compras no supermercado para apostar em bets, segundo dados de 2024, da Sociedade de Varejo e Consumo. Entretanto, para se enfrentar a ludopatia, é preciso, antes, vencer dois grandes desafios.',
    ],
    bestFor: "introdução",
  },
  {
    id: "011",
    title: "Tempos Modernos",
    type: "filme",
    category:
      "Trabalho / Industrialização / Tecnologia / Capitalismo / Desigualdade social / Condições de trabalho / Alienação",
    eixoTematico: ["Trabalho e economia"],
    specificThemes: [
      "Precarização do trabalho",
      "Condições de trabalho",
      "Exploração do trabalhador",
      "Direitos trabalhistas",
      "Proteção social do trabalhador",
      "Impactos da tecnologia no mercado de trabalho",
      "Automação e emprego",
      "Substituição da mão de obra",
      "Alienação no trabalho",
      "Pressão por produtividade",
      "Desigualdade nas relações de trabalho",
      "Trabalho informal",
      "Uberização do trabalho",
      "Trabalho por aplicativos",
      "Ausência de direitos trabalhistas",
      "Desemprego tecnológico",
      "Transformações no mercado de trabalho",
      "Relações entre tecnologia e trabalho",
      "Industrialização e condições sociais",
    ],
    keywords: [
      "tempos modernos",
      "trabalhador",
      "trabalho",
      "fábrica",
      "indústria",
      "industrialização",
      "capitalismo",
      "sistema industrial",
      "produção em massa",
      "linha de montagem",
      "mecanização",
      "máquinas",
      "tecnologia",
      "automação",
      "produtividade",
      "exploração do trabalhador",
      "condições de trabalho",
      "condições indignas de trabalho",
      "precarização do trabalho",
      "direitos trabalhistas",
      "desigualdade social",
      "desigualdade econômica",
      "classe trabalhadora",
      "proletariado",
      "alienação do trabalho",
      "trabalho repetitivo",
      "jornada de trabalho",
      "pressão por produtividade",
      "desemprego",
      "substituição da mão de obra",
      "tecnologia e trabalho",
      "impactos da tecnologia",
      "relações trabalhistas",
      "mercado de trabalho",
      "exploração econômica",
      "trabalho informal",
      "trabalho por aplicativos",
      "trabalhadores de aplicativos",
      "entregadores",
      "motoristas de aplicativo",
      "proteção trabalhista",
      "ausência de direitos",
      "uberização",
    ],
    explanation:
      'O filme "Tempos Modernos", dirigido e estrelado por Charlie Chaplin em 1936, acompanha um trabalhador de fábrica submetido ao ritmo intenso da produção industrial. Em meio a tarefas repetitivas e à pressão por produtividade, o personagem sofre com as exigências impostas pelas máquinas e pelas condições de trabalho. Com tom cômico, a obra critica os efeitos da industrialização sobre o trabalhador e evidencia problemas relacionados à exploração, à desumanização e à perda de autonomia no ambiente de trabalho.',
    essayUsage:
      "O repertório pode ser utilizado para discutir as consequências das transformações tecnológicas e econômicas sobre o trabalho e as condições de vida dos trabalhadores. É especialmente produtivo para temas relacionados à precarização profissional, aos direitos trabalhistas, à automação, à substituição da mão de obra, à exploração do trabalhador, à alienação no trabalho e à uberização.",
    usageTemplate:
      "Em seu icônico filme Tempos Modernos, de 1936, Charlie Chaplin apresenta um empregado de fábrica martirizado por máquinas que o levam para a prisão. Ainda que a obra tenha um evidente tom cômico, é inquestionável que o pano de fundo explorado por Chaplin é a sujeição do personagem a [problema]. Esse enredo, entretanto, não se restringe à ficção. No mundo todo, funções vistas como subalternas são muitas vezes deixadas à margem de direitos trabalhistas. Um exemplo contemporâneo dessa situação é a chamada uberização, situação em que prestadores de serviço são compelidos a arcarem com os custos do seu trabalho e a abrirem mão de férias, plano de saúde, aposentadoria, como ocorre com motoristas e entregadores de aplicativos. Para se enfrentar [tema] no Brasil, no entanto, é preciso vencer dois desafios principais.",
    usagePlaceholders: ["[problema]", "[tema]"],
    usageTips:
      "No campo [problema], coloque o principal problema relacionado ao trabalho apresentado pelo tema da redação; no campo [tema], reescreva com outras palavras o tema proposto pelo caderno de redação.",
    usageExample: [
      "Precarização do trabalho",
      "Em seu icônico filme Tempos Modernos, de 1936, Charlie Chaplin apresenta um empregado de fábrica martirizado por máquinas que o levam para a prisão. Ainda que a obra tenha um evidente tom cômico, é inquestionável que o pano de fundo explorado por Chaplin é a sujeição do personagem a condições indignas de trabalho. Esse enredo, entretanto, não se restringe à ficção. No mundo todo, funções vistas como subalternas são muitas vezes deixadas à margem de direitos trabalhistas. Um exemplo contemporâneo dessa situação é a chamada uberização, situação em que prestadores de serviço são compelidos a arcarem com os custos do seu trabalho e a abrirem mão de férias, plano de saúde, aposentadoria, como ocorre com motoristas e entregadores de aplicativos. Para se enfrentar essa precarização do trabalho no Brasil, no entanto, é preciso vencer dois desafios principais.",
    ],
    bestFor: "introdução",
  },
  {
    id: "012",
    title: "Casa-Grande & Senzala",
    type: "livro",
    category:
      "Formação social brasileira / Patriarcado / Desigualdade social / Relações de poder / Escravidão / Hierarquia social / Relações de gênero",
    eixoTematico: ["Cultura e sociedade"],
    specificThemes: [
      "Formação da sociedade brasileira",
      "Heranças sociais do período colonial",
      "Desigualdade social",
      "Desigualdade de gênero",
      "Patriarcado",
      "Dominação masculina",
      "Divisão sexual do trabalho",
      "Desvalorização do trabalho doméstico",
      "Trabalho de cuidado",
      "Reconhecimento do trabalho de cuidado",
      "Desigualdade nas relações de trabalho",
      "Papel social da mulher",
      "Relações de poder",
      "Herança da escravidão",
      "Consequências sociais da escravidão",
      "Hierarquização social",
      "Reprodução de desigualdades históricas",
      "Valorização dos profissionais da educação",
      "Reconhecimento social do professor",
      "Desvalorização profissional",
      "Educação e desigualdade social",
    ],
    keywords: [
      "casa-grande & senzala",
      "gilberto freyre",
      "formação social brasileira",
      "sociedade brasileira",
      "período colonial",
      "brasil colonial",
      "sociedade patriarcal",
      "patriarcado",
      "dominação masculina",
      "relações de gênero",
      "desigualdade de gênero",
      "hierarquia social",
      "relações de poder",
      "relações sociais",
      "estrutura social",
      "desigualdade social",
      "escravidão",
      "sociedade escravista",
      "trabalho escravo",
      "casa-grande",
      "senzala",
      "senhores de engenho",
      "engenho",
      "aristocracia rural",
      "elite colonial",
      "relações entre senhores e escravizados",
      "herança colonial",
      "legado da escravidão",
      "estrutura patriarcal",
      "poder masculino",
      "papel social da mulher",
      "divisão social do trabalho",
      "divisão sexual do trabalho",
      "trabalho doméstico",
      "trabalho de cuidado",
      "desvalorização do trabalho doméstico",
      "desvalorização do cuidado",
      "educação",
      "escola",
      "magistério",
      "profissão docente",
      "reconhecimento profissional",
      "prestígio social",
      "hierarquização das profissões",
      "desigualdade histórica",
      "organização familiar",
      "família patriarcal",
      "relações domésticas",
      "espaço doméstico",
      "cultura patriarcal",
    ],
    explanation:
      'Publicado em 1933, o livro "Casa-Grande & Senzala", de Gilberto Freyre, analisa a formação da sociedade brasileira a partir das relações entre senhores, pessoas escravizadas e outros grupos durante o período colonial. A obra destaca a influência da escravidão, do patriarcalismo e da organização dos engenhos na formação dos costumes, das relações familiares e da estrutura social brasileira. Freyre também aborda a hierarquia estabelecida entre a casa-grande e a senzala, evidenciando como essas relações contribuíram para a construção de desigualdades e de papéis sociais que permaneceram na sociedade brasileira.',
    essayUsage:
      "O repertório pode ser utilizado para discutir problemas relacionados à formação histórica da sociedade brasileira e à permanência de estruturas sociais construídas durante o período colonial. É especialmente produtivo para temas sobre desigualdade social e de gênero, patriarcado, divisão sexual do trabalho, desvalorização do trabalho doméstico e de cuidado, relações de poder, heranças da escravidão e reprodução de desigualdades históricas.",
    usageTemplate:
      'Um deles é [problema]. Essa expressão é uma referência aos [contexto]. Em sociedades patriarcais - baseadas na dominação masculina -, esse tipo de função é historicamente desprestigiado e visto como uma mera extensão das supostas obrigações da mulher. Como constata Gilberto Freyre, em seu livro "Casa Grande e Senzala", o magistério enquadra-se na persistência dessa lógica do período colonial, em que a escola é associada ao universo doméstico. Tal percepção faz com que professores tenham remuneração e reconhecimento não muito diferentes daqueles dedicados a outros profissionais que, na analogia de Freyre, servem à "Casa Grande", sem fazer jus a qualquer prestígio social.',
    usagePlaceholders: ["[problema]", "[contexto]"],
    usageTips:
      "No campo [problema], coloque o principal problema apresentado pelo tema da redação; em [contexto], explique a situação, atividade ou grupo ao qual o problema está relacionado.",
    usageExample: [
      "Desafios à valorização do professor no Brasil",
      'Um deles é a falta de reconhecimento dos chamados "trabalhos de cuidado". Essa expressão é uma referência aos afazeres voltados à atenção ao lar, a crianças e a idosos principalmente. Em sociedades patriarcais - baseadas na dominação masculina -, esse tipo de função é historicamente desprestigiado e visto como uma mera extensão das supostas obrigações da mulher. Como constata Gilberto Freyre, em seu livro "Casa Grande e Senzala", o magistério enquadra-se na persistência dessa lógica do período colonial, em que a escola é associada ao universo doméstico. Tal percepção faz com que professores tenham remuneração e reconhecimento não muito diferentes daqueles dedicados a outros profissionais que, na analogia de Freyre, servem à "Casa Grande", sem fazer jus a qualquer prestígio social.',
    ],
    bestFor: "desenvolvimento",
  },
  {
    id: "013",
    title: "A crise da educação no Brasil não é uma crise; é um projeto",
    type: "citação",
    category:
      "Educação / Desigualdade social / Políticas públicas / Cidadania / Sucateamento da educação / Desigualdade educacional",
    eixoTematico: ["Educação"],
    specificThemes: [
      "Desvalorização da educação pública",
      "Sucateamento das escolas públicas",
      "Desigualdade educacional",
      "Desigualdade de acesso à educação",
      "Qualidade do ensino público",
      "Financiamento da educação",
      "Investimento em educação",
      "Infraestrutura escolar",
      "Valorização dos professores",
      "Desvalorização docente",
      "Políticas públicas educacionais",
      "Democratização do acesso à educação",
      "Permanência escolar",
      "Evasão escolar",
      "Educação e desigualdade social",
      "Educação e cidadania",
      "Formação crítica dos estudantes",
      "Papel social da escola",
      "Educação como instrumento de transformação social",
      "Reprodução das desigualdades sociais",
      "Direito à educação",
      "Precarização da educação pública",
    ],
    keywords: [
      "a crise da educação no brasil não é uma crise; é um projeto",
      "darcy ribeiro",
      "educação brasileira",
      "educação pública",
      "escola pública",
      "crise educacional",
      "crise da educação",
      "projeto educacional",
      "sucateamento da educação",
      "precarização da educação",
      "negligência educacional",
      "abandono educacional",
      "desvalorização da educação",
      "qualidade do ensino",
      "ensino público",
      "desigualdade educacional",
      "desigualdade social",
      "acesso à educação",
      "permanência escolar",
      "políticas educacionais",
      "políticas públicas",
      "investimento em educação",
      "financiamento da educação",
      "infraestrutura escolar",
      "condições de ensino",
      "formação educacional",
      "professores",
      "valorização docente",
      "desvalorização do professor",
      "qualidade da educação",
      "ensino de qualidade",
      "democratização da educação",
      "educação e cidadania",
      "educação e transformação social",
      "educação e justiça social",
      "consciência crítica",
      "pensamento crítico",
      "formação cidadã",
      "participação social",
      "injustiça social",
      "reprodução das desigualdades",
      "manutenção das desigualdades",
      "exclusão social",
      "oportunidade educacional",
      "direito à educação",
      "direitos sociais",
      "papel da escola",
      "função social da educação",
      "educação formal",
      "acesso ao conhecimento",
      "ferramentas de transformação social",
    ],
    explanation:
      'A frase "A crise da educação no Brasil não é uma crise; é um projeto", atribuída ao antropólogo Darcy Ribeiro, expressa a ideia de que os problemas educacionais brasileiros não seriam resultado apenas de dificuldades circunstanciais, mas de um processo histórico de negligência e manutenção de uma educação de baixa qualidade. Nessa perspectiva, a precariedade do ensino limita o acesso da população ao conhecimento e à formação crítica, dificultando a compreensão e o questionamento das desigualdades sociais.',
    essayUsage:
      "O repertório pode ser utilizado para discutir problemas educacionais como consequência de decisões políticas e de processos históricos de negligência. É especialmente produtivo para temas relacionados ao sucateamento da educação pública, à desigualdade educacional, à qualidade do ensino, ao investimento em educação, à valorização dos professores e ao papel da escola na formação crítica e cidadã.",
    usageTemplate:
      'Além disso, [problema] está inserida em um projeto histórico de [argumento 2]. Esse propósito é traduzido pela célebre frase do antropólogo Darcy Ribeiro: "a crise da educação no Brasil não é uma crise; é um projeto". A lógica sustentada por Ribeiro é que o desprezo pela escola é algo funcional no país, uma vez que a má qualidade de ensino impede a maioria da população de ter acesso a ferramentas que lhes permitam perceber e questionar injustiças sociais. Nesse viés, [tema] passa por uma política de ampla reformulação da educação formal, de modo a que cada indivíduo entenda o papel estratégico dos docentes para a construção de uma sociedade mais justa.',
    usagePlaceholders: ["[problema]", "[argumento 2]", "[tema]"],
    usageTips:
      "No campo [problema], coloque o principal problema apresentado pelo tema da redação; no campo [argumento 2], coloque a segunda causa ou fator que contribui para a existência ou permanência do problema; no campo [tema], reescreva com outras palavras o tema proposto pelo caderno de redação.",
    usageExample: [
      "Desafios à valorização do professor no Brasil",
      'Além disso, a desvalorização do professor está inserida em um projeto histórico de sucateamento da escola no Brasil. Esse propósito é traduzido pela célebre frase do antropólogo Darcy Ribeiro: "a crise da educação no Brasil não é uma crise; é um projeto". A lógica sustentada por Ribeiro é que o desprezo pela escola é algo funcional no país, uma vez que a má qualidade de ensino impede a maioria da população de ter acesso a ferramentas que lhes permitam perceber e questionar injustiças sociais. Nesse viés, a valorização do professor passa por uma política de ampla reformulação da educação formal, de modo a que cada indivíduo entenda o papel estratégico dos docentes para a construção de uma sociedade mais justa.',
    ],
    bestFor: "desenvolvimento",
  },
  {
    id: "014",
    title: "Art. 205 da Constituição Federal de 1988",
    type: "lei",
    category:
      "Educação / Direitos sociais / Direitos fundamentais / Cidadania / Políticas públicas / Responsabilidade do Estado / Responsabilidade da família",
    eixoTematico: ["Educação"],
    specificThemes: [
      "Direito à educação",
      "Acesso à educação",
      "Universalização do ensino",
      "Desigualdade educacional",
      "Acesso desigual à educação",
      "Qualidade do ensino",
      "Educação pública",
      "Educação básica",
      "Evasão escolar",
      "Abandono escolar",
      "Permanência escolar",
      "Inclusão educacional",
      "Democratização da educação",
      "Responsabilidade do Estado na educação",
      "Participação da família na educação",
      "Políticas públicas educacionais",
      "Formação para a cidadania",
      "Educação e qualificação profissional",
      "Obstáculos ao acesso escolar",
      "Garantia dos direitos sociais",
    ],
    keywords: [
      "constituição federal de 1988",
      "constituição de 1988",
      "artigo 205",
      "art. 205",
      "educação",
      "direito à educação",
      "educação como direito",
      "direito fundamental",
      "direito social",
      "educação pública",
      "ensino",
      "acesso à educação",
      "acesso ao ensino",
      "educação para todos",
      "universalização da educação",
      "igualdade de acesso",
      "igualdade educacional",
      "dever do estado",
      "dever da família",
      "responsabilidade do estado",
      "responsabilidade da família",
      "políticas educacionais",
      "políticas públicas",
      "ensino público",
      "educação básica",
      "frequência escolar",
      "permanência escolar",
      "qualidade da educação",
      "ensino de qualidade",
      "formação educacional",
      "formação para a cidadania",
      "exercício da cidadania",
      "desenvolvimento da pessoa",
      "qualificação para o trabalho",
      "cidadania",
      "direitos sociais",
      "direitos fundamentais",
      "dignidade humana",
      "inclusão educacional",
      "democratização da educação",
      "desigualdade educacional",
      "exclusão educacional",
      "evasão escolar",
      "abandono escolar",
      "acesso universal ao ensino",
      "garantia de direitos",
      "proteção social",
      "estado e educação",
      "família e educação",
    ],
    explanation:
      "O artigo 205 da Constituição Federal de 1988 estabelece a educação como direito de todos e dever do Estado e da família, determinando que ela deve promover o pleno desenvolvimento da pessoa, prepará-la para o exercício da cidadania e qualificá-la para o trabalho. Dessa forma, o dispositivo constitucional define a educação como um direito fundamental e atribui ao poder público e à família responsabilidades pela sua garantia.",
    essayUsage:
      "O repertório pode ser utilizado para discutir situações em que o direito à educação não é plenamente garantido ou em que existem obstáculos ao acesso, à permanência e à qualidade do ensino. É especialmente produtivo para temas relacionados à desigualdade educacional, à evasão escolar, à inclusão, à educação pública, às políticas educacionais e à responsabilidade do Estado e da família na garantia desse direito.",
    usageTemplate:
      "Segundo o artigo 205 da Constituição Federal de 1988, a educação é um direito de todos e dever do Estado e da Família. Entretanto, a sociedade brasileira ainda está distante de concretizar esse preceito constitucional em sua plenitude. Isso porque vários problemas ainda impede [consequência]. Segundo [dado/exemplo/explicação], [comprovação do problema]. Isso deixa claro que para [tema], o Brasil precisa superar alguns desafios históricos.",
    usagePlaceholders: [
      "[consequência]",
      "[dado/exemplo/explicação]",
      "[comprovação do problema]",
      "[tema]",
    ],
    usageTips:
      "No campo [consequência], coloque um dos principais efeitos provocados pelo problema apresentado; em [dado/exemplo/explicação], coloque uma informação, situação concreta ou explicação que comprove ou contextualize o problema apresentado; em [comprovação do problema], apresente o dado, exemplo ou explicação selecionado de forma relacionada ao problema discutido; no campo [tema], reescreva com outras palavras o tema proposto pelo caderno de redação.",
    usageExample: [
      "A idade mínima para o trabalho como forma de proteção à infância",
      "Segundo o artigo 205 da Constituição Federal de 1988, a educação é um direito de todos e dever do Estado e da Família. Entretanto, a sociedade brasileira ainda está distante de concretizar esse preceito constitucional em sua plenitude. Isso porque vários problemas ainda impedem o acesso universal ao ensino. É o caso da persistência do trabalho infantil, que dificulta a frequência de muitas crianças às salas de aula ou atrapalha o aproveitamento adequado das disciplinas. Segundo o IBGE, em 2023, cerca de 1,6 milhão de crianças e adolescentes tinham algum vínculo empregatício, a despeito da legislação nacional, que veda o exercício de atividades laborais a menores de 14 anos. Isso deixa claro que para fazer valer a idade mínima para o trabalho como forma de proteção à infância, o Brasil precisa superar alguns desafios históricos.",
    ],
    bestFor: "introdução",
  },
  {
    id: "015",
    title: "1984",
    type: "livro",
    category:
      "Autoritarismo / Manipulação da informação / Controle social / Vigilância / Liberdade de expressão / Poder político",
    eixoTematico: ["Política e relações sociais"],
    specificThemes: [
      "Fake news",
      "Desinformação",
      "Manipulação da informação",
      "Disseminação de notícias falsas",
      "Impactos da desinformação na sociedade",
      "Liberdade de expressão",
      "Liberdade de imprensa",
      "Censura",
      "Controle da informação",
      "Manipulação da opinião pública",
      "Propaganda política",
      "Influência da mídia",
      "Vigilância social",
      "Privacidade",
      "Monitoramento tecnológico",
      "Autoritarismo",
      "Totalitarismo",
      "Abuso de poder",
      "Controle social",
      "Pensamento crítico",
      "Acesso à informação",
      "Manipulação política",
      "Enfraquecimento da democracia",
      "Preservação da memória histórica",
    ],
    keywords: [
      "1984",
      "george orwell",
      "distopia",
      "estado totalitário",
      "totalitarismo",
      "autoritarismo",
      "controle estatal",
      "controle social",
      "vigilância",
      "vigilância constante",
      "manipulação da informação",
      "manipulação da verdade",
      "distorção da informação",
      "desinformação",
      "fake news",
      "notícias falsas",
      "propaganda política",
      "propaganda",
      "censura",
      "controle da imprensa",
      "controle da mídia",
      "controle da comunicação",
      "controle do pensamento",
      "liberdade de expressão",
      "liberdade de informação",
      "acesso à informação",
      "verdade",
      "fatos",
      "realidade",
      "opinião",
      "narrativa política",
      "discurso político",
      "poder político",
      "abuso de poder",
      "repressão",
      "perseguição",
      "monitoramento",
      "privacidade",
      "invasão de privacidade",
      "tecnologia e vigilância",
      "sociedade vigiada",
      "pensamento crítico",
      "alienação",
      "doutrinação",
      "revisionismo histórico",
      "manipulação da história",
      "apagamento da memória",
      "formação da opinião pública",
      "influência política",
      "democracia",
      "enfraquecimento democrático",
      "manipulação social",
    ],
    explanation:
      'Publicado em 1949, o romance "1984", de George Orwell, apresenta uma sociedade distópica submetida ao controle de um Estado totalitário. A população é constantemente vigiada e tem sua liberdade limitada por mecanismos de repressão e manipulação da informação. O governo altera registros históricos e divulga versões dos fatos que atendem aos seus interesses, dificultando a distinção entre verdade e falsidade. Dessa forma, a obra aborda os efeitos do controle da informação, da vigilância e da manipulação da realidade sobre a liberdade e o pensamento dos indivíduos.',
    essayUsage:
      "O repertório pode ser utilizado para discutir situações em que a manipulação da informação ou o controle social comprometem a autonomia dos indivíduos e o funcionamento da sociedade. É especialmente produtivo para temas relacionados à desinformação, às fake news, à liberdade de expressão, à censura, à propaganda política, à vigilância, à privacidade e aos riscos do autoritarismo.",
    usageTemplate:
      'No romance "1984", George Orwell projeta um futuro distópico em que o Estado controla todos os aspectos da vida humana. Na obra, esse domínio não se dá por meio de armas ou da truculência física, mas da manipulação da informação. A distorção deliberada de fatos e a criação de narrativas mirabolantes dificultam aos cidadãos distinguirem verdade de meras opiniões, o que enfraquece o discurso político sério. O que Orwell imaginou na ficção, [problema] trouxe para a vida real: a distorção de notícias para a criação de realidades paralelas. Exemplo disso foi [dado/exemplo/explicação]. Essas [consequência] oferecem vários riscos à vida em sociedade.',
    usagePlaceholders: [
      "[problema]",
      "[dado/exemplo/explicação]",
      "[consequência]",
    ],
    usageTips:
      "No campo [problema], coloque o principal problema apresentado pelo tema da redação; em [dado/exemplo/explicação], coloque uma informação, situação concreta ou explicação que comprove ou contextualize o problema apresentado; no campo [consequência], coloque os efeitos provocados pelo problema na sociedade.",
    usageExample: [
      "Os riscos das fake news à vida em sociedade",
      'No romance "1984", George Orwell projeta um futuro distópico em que o Estado controla todos os aspectos da vida humana. Na obra, esse domínio não se dá por meio de armas ou da truculência física, mas da manipulação da informação. A distorção deliberada de fatos e a criação de narrativas mirabolantes dificultam aos cidadãos distinguirem verdade de meras opiniões, o que enfraquece o discurso político sério. O que Orwell imaginou na ficção, o uso inescrupuloso da internet trouxe para a vida real: a distorção de notícias para a criação de realidades paralelas. Exemplo disso foi o discurso antivacina e em defesa de tratamentos inócuos disseminados em redes sociais durante a recente pandemia de covid-19. Essas fake news, como ficaram conhecidas, oferecem vários riscos à vida em sociedade.',
    ],
    bestFor: "introdução",
  },
  {
    id: "016",
    title: "Salve Rosa",
    type: "filme",
    category:
      "Infância e adolescência / Exposição digital / Redes sociais / Privacidade / Exploração infantil / Monetização de conteúdo / Responsabilidade familiar",
    eixoTematico: ["Tecnologia e inovação"],
    specificThemes: [
      "Exposição de crianças e adolescentes na internet",
      "Superexposição infantil nas redes sociais",
      "Privacidade de crianças e adolescentes no ambiente digital",
      "Exploração comercial da imagem de menores",
      "Monetização de conteúdo infantil",
      "Influenciadores mirins",
      "Produção de conteúdo por crianças e adolescentes",
      "Publicidade envolvendo menores",
      "Riscos da exposição precoce nas redes sociais",
      "Proteção da infância no ambiente digital",
      "Segurança de crianças na internet",
      "Responsabilidade dos pais sobre a exposição dos filhos",
      "Uso da imagem de menores na internet",
      "Influência das plataformas digitais sobre crianças",
      "Vulnerabilidade de menores no ambiente digital",
      "Consequências da exposição excessiva nas redes sociais",
    ],
    keywords: [
      "salve rosa",
      "internet",
      "redes sociais",
      "plataformas digitais",
      "conteúdo infantil",
      "conteúdo juvenil",
      "crianças na internet",
      "adolescentes na internet",
      "exposição infantil",
      "exposição de menores",
      "exposição digital",
      "superexposição",
      "privacidade",
      "privacidade infantil",
      "proteção da infância",
      "proteção de menores",
      "exploração infantil",
      "exploração comercial",
      "monetização de conteúdo",
      "geração de receita",
      "publicidade infantil",
      "influência digital",
      "influenciadores mirins",
      "influenciadores adolescentes",
      "produção de conteúdo",
      "criação de conteúdo",
      "imagem de crianças",
      "imagem de menores",
      "uso da imagem",
      "exposição da vida privada",
      "riscos da internet",
      "segurança digital",
      "vulnerabilidade infantil",
      "vulnerabilidade de crianças e adolescentes",
      "responsabilidade dos pais",
      "responsabilidade familiar",
      "redes sociais e infância",
      "plataformas digitais e crianças",
    ],
    explanation:
      'O filme "Salve Rosa" retrata a angustiante realidade de Rosa, uma jovem cuja vida e privacidade são expostas e manipuladas por sua própria mãe na busca obsessiva por engajamento digital. Ao utilizar a imagem da filha para atrair o público infantil e acumular visualizações, a mãe coloca a métrica de likes e o sucesso nas redes sociais acima da saúde mental, da segurança e das necessidades fundamentais da garota. Com uma abordagem crítica e extremamente atual, a obra expõe os perigos da superexposição e da exploração de menores na internet, além de discutir os limites éticos do universo dos influenciadores digitais e a mercantilização do afeto no ambiente familiar.',
    essayUsage:
      "Pode ser utilizado em temas relacionados à exposição de crianças e adolescentes na internet, à privacidade e proteção de menores no ambiente digital, à exploração comercial da imagem infantil, à monetização de conteúdos com menores e aos riscos da produção de conteúdo por crianças e adolescentes. O repertório é especialmente produtivo para discutir como interesses financeiros e a busca por visualizações podem contribuir para a exposição excessiva de menores.",
    usageTemplate:
      'O filme "#SalveRosa" retrata a angustiante realidade de Rosa, uma jovem cuja vida e privacidade são expostas e manipuladas por sua própria mãe na busca obsessiva por engajamento digital. Ao utilizar a imagem da filha para atrair o público infantil e acumular visualizações, a mãe coloca o sucesso nas redes sociais acima da saúde mental e da segurança da garota. Embora se trate de uma ficção, essa situação pode ser observada na realidade brasileira. Segundo [dado/exemplo/explicação]. Tal fenômeno demonstra a quantidade de jovens que podem ser manipulados e transformados em geradores de receita para grandes plataformas digitais. Para combater [tema], é preciso vencer dois principais desafios.',
    usagePlaceholders: ["[dado/exemplo/explicação]", "[tema]"],
    usageTips:
      "No campo [dado/exemplo/explicação], coloque uma informação, situação concreta ou explicação que comprove ou contextualize o problema apresentado; no campo [tema], reescreva com outras palavras o tema proposto pelo caderno de redação.",
    usageExample: [
      "A exposição indiscriminada de crianças e adolescentes na internet",
      'O filme "Salve Rosa" gira em torno da vida de Rosa, que produz conteúdo juvenil para a internet. A obra deixa explícitas ações extremistas da mãe da personagem por interesse financeiro, visto que a imagem infantil atraía crianças e visualizações. Embora se trate de uma ficção, essa produção pode ser reiterada na realidade brasileira. Segundo o site Tik Kids Online, em 2023, o número de crianças entre 9 e 10 anos que possuem perfil em plataformas digitais chegou a 68%. Tal fenômeno demonstra a quantidade de jovens que podem ser manipulados e transformados em geradores de receita para grandes plataformas digitais. Para combater a exposição indiscriminada de crianças e adolescentes na internet, é preciso vencer dois principais desafios.',
    ],
    bestFor: "introdução",
  },
  {
    id: "017",
    title: "Capitães da Areia",
    type: "livro",
    category:
      "Infância e adolescência / Vulnerabilidade social / Desigualdade social / Abandono / Trabalho infantil / Criminalidade / Exclusão social / Pobreza",
    eixoTematico: ["Desigualdade e inclusão"],
    specificThemes: [
      "Crianças e adolescentes em situação de rua",
      "Vulnerabilidade social na infância",
      "Abandono de crianças e adolescentes",
      "Trabalho infantil",
      "Exploração de menores",
      "Pobreza infantil",
      "Desigualdade social e infância",
      "Exclusão social de jovens",
      "Marginalização de crianças e adolescentes",
      "Criminalidade juvenil",
      "Falta de proteção à infância",
      "Garantia dos direitos das crianças e adolescentes",
      "Assistência social",
      "Acesso de jovens a direitos básicos",
      "Impactos da pobreza na infância",
      "Negligência do poder público",
      "Desigualdade econômica",
      "Oportunidades para jovens",
    ],
    keywords: [
      "capitães da areia",
      "jorge amado",
      "crianças em situação de rua",
      "crianças abandonadas",
      "infância vulnerável",
      "adolescência vulnerável",
      "vulnerabilidade social",
      "situação de rua",
      "abandono infantil",
      "desigualdade social",
      "desigualdade econômica",
      "pobreza",
      "exclusão social",
      "marginalização",
      "trabalho infantil",
      "exploração infantil",
      "sobrevivência",
      "criminalidade juvenil",
      "pequenos delitos",
      "violência",
      "falta de acesso a direitos",
      "negligência social",
      "ausência do estado",
      "proteção à infância",
      "direitos da criança",
      "direitos dos adolescentes",
      "assistência social",
      "desigualdade no brasil",
      "infância e pobreza",
      "juventude e vulnerabilidade",
    ],
    explanation:
      'Publicado em 1937 por Jorge Amado, "Capitães da Areia" retrata o cotidiano de um grupo de crianças e adolescentes abandonados que vive em um trapiche no cais de Salvador, sobrevivendo por meio de pequenos furtos e da cumplicidade mútua. Liderados por Pedro Bala, esses jovens marginalizados enfrentam a repressão policial, o preconceito e a extrema pobreza de uma sociedade que prefere puni-los a acolhê-los. Com forte carga de denúncia social e sensibilidade poética, a narrativa contrapõe a perda precoce da inocência à busca por liberdade e afeto, demonstrando como a exclusão social molda o destino desses meninos. Ao amadurecerem, eles transformam a revolta vivenciada nas ruas em consciência política e luta por transformação social.',
    essayUsage:
      "Pode ser utilizado em temas relacionados à vulnerabilidade de crianças e adolescentes, situação de rua, trabalho infantil, pobreza, desigualdade social, abandono, exclusão e criminalidade juvenil. O repertório é especialmente produtivo para discutir como a ausência de condições básicas e de proteção social pode expor jovens a situações de exploração, violência e marginalização.",
    usageTemplate:
      "O livro Capitães da Areia, de Jorge Amado, narra a trajetória de crianças que viviam à própria sorte nas ruas de Salvador. Na obra, os menores se veem forçados a trabalhar e até a praticar pequeno delito para sobreviver. Infelizmente, a história contada pelo escritor baiano está longe de ser mera ficção. Segundo [dado/exemplo/explicação]. Diante disso, para enfrentar [tema] é preciso vencer dois desafios.",
    usagePlaceholders: ["[dado/exemplo/explicação]", "[tema]"],
    usageTips:
      "No campo [dado/exemplo/explicação], coloque uma informação, situação concreta ou explicação que comprove ou contextualize o problema apresentado; no campo [tema], reescreva com outras palavras o tema proposto pelo caderno de redação.",
    usageExample: [
      "A vulnerabilidade de crianças e adolescentes no Brasil",
      "O livro Capitães da Areia, de Jorge Amado, narra a trajetória de crianças que viviam à própria sorte nas ruas de Salvador. Na obra, os menores se veem forçados a trabalhar e até a praticar pequeno delito para sobreviver. Infelizmente, a história contada pelo escritor baiano está longe de ser mera ficção. Segundo o IBGE, em 2023, cerca de 1.600.000 crianças e adolescentes trabalhavam no Brasil. Diante disso, para enfrentar a vulnerabilidade dos jovens no país é preciso vencer dois desafios.",
    ],
    bestFor: "introdução",
  },
  {
    id: "018",
    title: "Não Olhe Para Cima",
    type: "filme",
    category:
      "Mudanças climáticas / Negacionismo científico / Desinformação / Mídia e comunicação / Opinião pública / Interesses políticos e econômicos / Crises ambientais / Responsabilidade coletiva",
    eixoTematico: ["Meio ambiente"],
    specificThemes: [
      "Mudanças climáticas",
      "Negacionismo científico",
      "Desinformação ambiental",
      "Politização da ciência",
      "Impactos do aquecimento global",
      "Fenômenos climáticos extremos",
      "Influência de interesses econômicos nas questões ambientais",
      "Responsabilidade diante da crise climática",
    ],
    keywords: [
      "não olhe para cima",
      "adam mckay",
      "mudanças climáticas",
      "crise climática",
      "aquecimento global",
      "emergência climática",
      "negacionismo climático",
      "negacionismo científico",
      "ciência",
      "descrédito da ciência",
      "politização da ciência",
      "desinformação",
      "manipulação da informação",
      "manipulação da opinião pública",
      "opinião pública",
      "mídia",
      "meios de comunicação",
      "redes sociais",
      "comunicação científica",
      "divulgação científica",
      "percepção de riscos",
      "riscos ambientais",
      "ameaça coletiva",
      "catástrofe",
      "crise ambiental",
      "desastres ambientais",
      "interesses políticos",
      "interesses econômicos",
      "interesses corporativos",
      "poder político",
      "influência política",
      "negligência ambiental",
      "inação",
      "mobilização social",
      "responsabilidade coletiva",
      "políticas ambientais",
      "tomada de decisão",
      "preservação ambiental",
      "impactos ambientais",
    ],
    explanation:
      'O filme "Não Olhe Para Cima", dirigido por Adam McKay, acompanha dois astrônomos que descobrem que um cometa está em rota de colisão com a Terra e provocará uma catástrofe em poucos meses. Ao perceberem a gravidade da situação, os cientistas procuram autoridades, meios de comunicação e outras instituições para alertar a população e tentar impedir o desastre. Entretanto, seus alertas são recebidos com descrédito, enquanto políticos e empresários passam a considerar os possíveis benefícios econômicos da situação. A mídia também transforma a ameaça em espetáculo, tratando uma questão científica e de sobrevivência coletiva como entretenimento e disputa política. Paralelamente, parte da população passa a rejeitar as evidências apresentadas pelos cientistas, influenciada por discursos políticos e informações distorcidas. Dessa forma, o filme critica o negacionismo científico, a manipulação da informação e a dificuldade de mobilização social diante de ameaças que exigem respostas coletivas. Embora a narrativa utilize a colisão de um cometa como ameaça central, a obra também estabelece uma relação com problemas ambientais contemporâneos, especialmente as mudanças climáticas, tendo sido inspirada pela frustração do diretor diante da forma como evidências científicas sobre o aquecimento global são frequentemente ignoradas ou politizadas.',
    essayUsage:
      "Pode ser utilizado para discutir a dificuldade de reconhecimento e enfrentamento de problemas ambientais e de risco, especialmente aqueles relacionados às mudanças climáticas. Também permite abordar o negacionismo científico, a desinformação, a influência de interesses políticos e econômicos sobre decisões ambientais e a responsabilidade coletiva diante de ameaças que afetam toda a sociedade.",
    usageTemplate:
      'O filme "Não Olhe Para Cima" conta a história de dois astrônomos que descobrem um cometa em rota de colisão com a Terra. Imediatamente, eles procuram as autoridades e a mídia para alertar sobre a iminente catástrofe. No entanto, esbarram na incredulidade das pessoas de que algo tão chocante possa de fato acontecer. Esse enredo parece traduzir perfeitamente a atual postura negacionista da sociedade quanto a uma ameaça real e próxima: [problema]. De acordo com [dado/exemplo/explicação]. Entretanto, tão importante quanto elencar os [tema], é analisar as suas causas.',
    usagePlaceholders: ["[problema]", "[dado/exemplo/explicação]", "[tema]"],
    usageTips:
      "No campo [problema], coloque o principal problema relacionado ao tema da redação. No campo [dado/exemplo/explicação], coloque uma informação, situação concreta ou explicação que comprove ou contextualize o problema apresentado. No campo [tema], coloque o tema proposto pelo caderno de redação, mantendo o sentido central da discussão.",
    usageExample: [
      "Os efeitos dos fenômenos climáticos extremos no Brasil",
      'O filme "Não Olhe Para Cima" conta a história de dois astrônomos que descobrem um cometa em rota de colisão com a Terra. Imediatamente, eles procuram as autoridades e a mídia para alertar sobre a iminente catástrofe. No entanto, esbarram na incredulidade das pessoas de que algo tão chocante possa de fato acontecer. Esse enredo parece traduzir perfeitamente a atual postura negacionista da sociedade quanto a uma ameaça real e próxima: os extremos climáticos. De acordo com a ONU, entre 2000 e 2019, cerca de 4 bilhões de pessoas foram afetadas por fenômenos naturais desproporcionais, como a grande enchente de 2024, no Rio Grande do Sul, que causou quase 200 mortes. Entretanto, tão importante quanto elencar os efeitos dessas calamidades no país, é analisar as suas causas.',
    ],
    bestFor: "introdução",
  },
];
